# Generated by Django 5.2.6 on 2025-10-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Título")),
                (
                    "url",
                    models.CharField(
                        help_text="Pode ser um caminho relativo ou URL completa",
                        max_length=200,
                        verbose_name="URL",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Ordem")),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "open_in_new_tab",
                    models.BooleanField(
                        default=False, verbose_name="Abrir em nova aba"
                    ),
                ),
            ],
            options={
                "verbose_name": "Item do Menu",
                "verbose_name_plural": "Itens do Menu",
                "ordering": ["order", "title"],
            },
        ),
        migrations.CreateModel(
            name="SiteConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(
                        default="Jornal do Commercio",
                        max_length=200,
                        verbose_name="Nome do Site",
                    ),
                ),
                (
                    "site_description",
                    models.TextField(blank=True, verbose_name="Descrição"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="site/", verbose_name="Logo"
                    ),
                ),
                (
                    "favicon",
                    models.ImageField(
                        blank=True, null=True, upload_to="site/", verbose_name="Favicon"
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email de Contato"
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Telefone"
                    ),
                ),
                ("facebook_url", models.URLField(blank=True, verbose_name="Facebook")),
                ("twitter_url", models.URLField(blank=True, verbose_name="Twitter")),
                (
                    "instagram_url",
                    models.URLField(blank=True, verbose_name="Instagram"),
                ),
            ],
            options={
                "verbose_name": "Configuração do Site",
                "verbose_name_plural": "Configurações do Site",
            },
        ),
    ]
