# Generated by Django 5.2.8 on 2025-11-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornal_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='autor_fonte',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Autor/Fonte Externa'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='imagem_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL da Imagem'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='url_fonte',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL da Fonte Original'),
        ),
    ]
