# Generated by Django 5.2.5 on 2025-11-17 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornal_app', '0003_alter_comentario_ativo_alter_comentario_autor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontos', models.IntegerField(default=0, verbose_name='Pontos')),
                ('nivel', models.IntegerField(default=1, verbose_name='Nível')),
                ('noticias_lidas', models.IntegerField(default=0, verbose_name='Notícias Lidas')),
                ('comentarios_feitos', models.IntegerField(default=0, verbose_name='Comentários Feitos')),
                ('categorias_visitadas', models.JSONField(blank=True, default=list, verbose_name='Categorias Visitadas')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('ultima_atividade', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil do Usuário',
                'verbose_name_plural': 'Perfis dos Usuários',
            },
        ),
    ]
