# Generated by Django 5.2.6 on 2025-10-28 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LiveEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                ("description", models.TextField(verbose_name="Descrição")),
                (
                    "stream_url",
                    models.URLField(blank=True, verbose_name="URL da Transmissão"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Ao Vivo"),
                ),
                ("scheduled_at", models.DateTimeField(verbose_name="Agendado para")),
                (
                    "ended_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Finalizado em"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento ao Vivo",
                "verbose_name_plural": "Eventos ao Vivo",
                "ordering": ["-scheduled_at"],
            },
        ),
    ]
