# Generated by Django 5.2.6 on 2025-10-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Advertisement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                (
                    "image",
                    models.ImageField(upload_to="advertising/", verbose_name="Imagem"),
                ),
                ("link", models.URLField(blank=True, verbose_name="Link")),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("header", "Header"),
                            ("sidebar", "Sidebar"),
                            ("footer", "Footer"),
                            ("between_content", "Entre Conteúdo"),
                        ],
                        max_length=20,
                        verbose_name="Posição",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                ("start_date", models.DateField(verbose_name="Data de Início")),
                ("end_date", models.DateField(verbose_name="Data de Término")),
                ("clicks", models.IntegerField(default=0, verbose_name="Cliques")),
            ],
            options={
                "verbose_name": "Anúncio",
                "verbose_name_plural": "Anúncios",
                "ordering": ["-start_date"],
            },
        ),
    ]
