# Generated by Django 5.2.6 on 2025-10-12 22:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornal_app', '0002_alter_categoria_options_alter_noticia_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='exclusiva',
            field=models.BooleanField(default=False, help_text='Marque se esta notícia é apenas para assinantes.', verbose_name='Conteúdo Exclusivo'),
        ),
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ATIVA', 'Ativa'), ('CANCELADA', 'Cancelada'), ('EXPIRADA', 'Expirada'), ('INADIMPLENTE', 'Inadimplente')], default='ATIVA', max_length=20)),
                ('data_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_fim', models.DateTimeField()),
                ('renovacao_automatica', models.BooleanField(default=True)),
                ('id_assinatura_gateway', models.CharField(blank=True, help_text='ID da assinatura gerado pelo gateway de pagamento (ex: Stripe, Pagar.me)', max_length=100, null=True, unique=True)),
                ('id_cliente_gateway', models.CharField(blank=True, help_text='ID do cliente gerado pelo gateway de pagamento', max_length=100, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assinatura',
                'verbose_name_plural': 'Assinaturas',
                'ordering': ['-data_fim'],
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
