# Generated by Django 5.2.6 on 2025-10-21 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jornal_app', '0003_noticia_exclusiva_assinatura_perfil'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Assinatura',
        ),
    ]
