# Generated by Django 5.2.6 on 2025-10-21 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornal_app', '0004_delete_assinatura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='exclusiva',
        ),
        migrations.AddField(
            model_name='noticia',
            name='destaque',
            field=models.BooleanField(default=False, help_text='Marque para que esta notícia apareça na seção de destaques da homepage.', verbose_name='Notícia em Destaque'),
        ),
    ]
